SELECT MiddleName, COUNT(FirstName) AS 'CONTAGEM'
FROM Person.Person
GROUP BY MiddleName


/*MÉDIA DE CADA PRODUTO VENDIDO*/
SELECT ProductID, AVG(ORDERQTY) AS 'QUANTIDADE' 
FROM Sales.SalesOrderDetail
GROUP BY ProductID

/*10 PRODUTOS MAIS VENDIDOS NO TOTAL DO MAIOR PARA MENOR*/
SELECT TOP 10 ProductID, SUM(LINETOTAL)
FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY SUM(LineTotal) DESC

/*QUANTIDADE DE PRODUTOS E QUANTIDADE MÉDIA DE CADA PRODUTO*/
SELECT ProductID, COUNT(ProductID) 'CONTAGEM', AVG(ORDERQTY) 'MEDIA'
FROM Production.WorkOrder
GROUP  BY PRODUCTID





