/*ESTADOS COM MAIS CADASTROS NO SISTEMA(ACIMA DE 1000)*/

SELECT StateProvinceID, COUNT(STATEPROVINCEID) AS 'QTD'
FROM Person.Address
GROUP BY StateProvinceID
HAVING COUNT(STATEPROVINCEID) > 1000

/*PRODUTOS COM MEDIA 1M*/

SELECT ProductID, AVG(LineTotal) AS 'MEDIA'
FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING AVG(LINETOTAL) < 1000000

