SELECT FIRSTNAME, COUNT(FIRSTNAME) AS 'QUANTIDADE'
FROM Person.Person
GROUP BY FirstName
HAVING COUNT(FIRSTNAME) > 10

SELECT TOP 10 *
FROM Sales.SalesOrderDetail

/*QUAIS PRODUTOS NO TOTAL ESTA ENTRE 160K E 500K*/
SELECT PRODUCTID, SUM(LINETOTAL) AS 'TOTAL'
FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING SUM(LINETOTAL) BETWEEN 160000 AND 500000

/*QUAIS NOMES TEM OCORRENCIA 10 VERZES COM TITULO 'MR'*/

SELECT FIRSTNAME, COUNT(FIRSTNAME) AS 'QUANTIDADE'
FROM Person.Person
WHERE Title = 'MR.'
GROUP BY FirstName
HAVING COUNT(FIRSTNAME) > 10
