/*LEFT JOIN INTERESSANTE PARA EXTRAIR DADOS DE ONDE NÃO TEM, EXEMPLO: CLIENTES QUE NAO TEM CARTÃO DE CREDITO*/

SELECT *
FROM Person.Person PP
LEFT JOIN Sales.PersonCreditCard PC
ON PP.BusinessEntityID = PC.BusinessEntityID
WHERE PC.BusinessEntityID IS NULL --ENCONTRAR PESSOAS SEM CREDIT CARD
-- INNER JOIN : 19118 LINHAS
-- LEFT JOIN: 19972 LINHAS